name: fixit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.0.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.1
  share_plus: ^10.1.4
  fluttertoast: ^8.2.4
  firebase_dynamic_links: ^6.1.2 # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
